const stationList = [
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.122.10.142",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "0-10.122.10.142",
    tagBind: "京九线.永修城际车间.K23线路所",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.165.218",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "1-10.239.165.218",
    tagBind: "京九线.吉安车间.八都站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.254",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "2-10.144.214.254",
    tagBind: "京九线.信丰车间.大塘阜线路所",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.154",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "3-10.144.214.154",
    tagBind: "京九线.吉安车间.大洋洲站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.227",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "4-10.144.214.227",
    tagBind: "京九线.信丰车间.定南站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.181.183",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "5-10.239.181.183",
    tagBind: "京九线.鹰潭信号车间.东乡站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.250",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "6-10.144.214.250",
    tagBind: "京九线.赣州车间.赣州南站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.202",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "7-10.144.214.202",
    tagBind: "京九线.赣州车间.赣州站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.186",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "8-10.144.214.186",
    tagBind: "京九线.兴国车间.高兴镇站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.226",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "9-10.144.214.226",
    tagBind: "京九线.信丰车间.关西镇站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.146",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "10-10.144.214.146",
    tagBind: "京九线.兴国车间.冠朝站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.171.8",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "11-10.144.171.8",
    tagBind: "京九线.庐山城际车间.黄梅南",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.170",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "12-10.144.214.170",
    tagBind: "京九线.吉安车间.吉水站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.181.215",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "13-10.239.181.215",
    tagBind: "京九线.向塘信号车间.进贤站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.5.242",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "14-10.239.5.242",
    tagBind: "京九线.南昌车间.莲塘站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.210",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "15-10.144.214.210",
    tagBind: "京九线.赣州车间.龙回站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.187",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "16-10.144.214.187",
    tagBind: "京九线.兴国车间.龙口站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.219",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "17-10.144.214.219",
    tagBind: "京九线.信丰车间.龙南站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.131",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "18-10.144.214.131",
    tagBind: "京九线.南昌车间.南昌Ⅱ场站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.130",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "19-10.144.214.130",
    tagBind: "京九线.南昌车间.南昌北站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.238.210",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "20-10.239.238.210",
    tagBind: "京九线.南昌车间.南昌站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.188",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "21-10.144.214.188",
    tagBind: "京九线.兴国车间.南塘镇站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.5.142",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "22-10.239.5.142",
    tagBind: "京九线.南昌车间.青云谱站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.179",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "23-10.144.214.179",
    tagBind: "京九线.兴国车间.沙村站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.5.243",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "24-10.239.5.243",
    tagBind: "京九线.南昌车间.生米站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.147",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "25-10.144.214.147",
    tagBind: "京九线.兴国车间.泰和站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.218",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "26-10.144.214.218",
    tagBind: "京九线.信丰车间.铁石口站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.194",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "27-10.144.214.194",
    tagBind: "京九线.樟树车间.拖船阜站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.181.231",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "28-10.239.181.231",
    tagBind: "京九线.向塘信号车间.温家圳站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.162",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "29-10.144.214.162",
    tagBind: "京九线.吉安车间.峡江普速场",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.24.94",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "30-10.239.24.94",
    tagBind: "京九线.向塘信号车间.向塘物流基地",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.220",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "31-10.144.214.220",
    tagBind: "京九线.信丰车间.小江站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.155",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "32-10.144.214.155",
    tagBind: "京九线.吉安车间.新干站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.211",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "33-10.144.214.211",
    tagBind: "京九线.信丰车间.信丰站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.181.199",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "34-10.239.181.199",
    tagBind: "京九线.向塘信号车间.衙前站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.144.214.178",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "35-10.144.214.178",
    tagBind: "京九线.兴国车间.营盘上站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.181.167",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "36-10.239.181.167",
    tagBind: "京九线.鹰潭信号车间.余江站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
  {
    acqAlarm: false,
    acqInterval: 30.0,
    acqMode: "all",
    addr: {
      ip: "10.239.165.219",
      port: 9999,
    },
    addrMode: "tcpServer",
    enableAcq: true,
    level: "devcie",
    manageStatus: "managed",
    nodeID: "37-10.239.165.219",
    tagBind: "京九线.吉安车间.醪桥站",
    type: "dcqk-sys-device",
    typeLabel: "道岔缺口站机",
  },
];

const digTree = stationList.reduce((acc, item) => {
  const {
    tagBind,
    addr: { ip },
  } = item;
  const [line, workshop, station] = tagBind.split(".");
  
  // 查找是否已存在该线路
  let lineNode = acc.find((item) => item.name === line);
  
  if (!lineNode) {
    // 如果线路不存在，创建新的线路节点
    lineNode = {
      name: line,
      id: `line_${line}`,
      children: []
    };
    acc.push(lineNode);
  }
  
  // 查找是否已存在该车间
  let workshopNode = lineNode.children.find((item) => item.name === workshop);
  
  if (!workshopNode) {
    // 如果车间不存在，创建新的车间节点
    workshopNode = {
      name: workshop,
      id: `workshop_${workshop}`,
      children: []
    };
    lineNode.children.push(workshopNode);
  }
  
  // 添加站点节点
  const stationNode = {
    name: station,
    id: `station_${station}_${ip}`,
    ip: ip,
    httpport: 81
  };
  workshopNode.children.push(stationNode);
  
  return acc;
}, []);

export default digTree;
